# The address prefix used for cosmos based addresses
address_prefix = "osmo"

# Fees to be sent with the transaction
fees = "10000uosmo"

# Gas Limit. "auto" attempts to do this automatically
gas = "auto"
# gas = "250000"

# The multiplier on gas estimates

# GRPC Server Address
# grpc_server_address = "osmosis-testnet-grpc.polkachu.com:12590"
grpc_server_address = "osmosis-grpc.polkachu.com:12590"

# The memo to be sent with the transaction
memo = "flood"

# RPC Server Address
# rpc_server_address = "https://osmosis-testnet-rpc.polkachu.com:443"
# rpc_server_address = "https://osmosis-rpc.polkachu.com:443"
# rpc_server_address = "https://rpc-testnet.margined.io:443"
websocket_path = "/websocket"
# rpc_server_address = "https://osmosis-testnet-api.polkachu.com:443"
rpc_server_address = "https://rpc.margined.io:443"

# The signer account
# signer_account = "liquidity-provider"
signer_account = "lp-atom"

[key]
app_name = "osmosis"
backend  = "pass"
# backend  = "os"
root_dir = "/Users/wandlitz"

[power_pool]
base_asset  = "factory/osmo1g8qypve6l95xmhgc0fddaecerffymsl7kn9muw/sqatom"
pool_id     = 1299
quote_asset = "ibc/27394FB092D2ECCD56123C74F36E4C1F926001CEADA9CA97EA622B25F41E5EB2"

[position]
default_token_0_amount = 3834048982
default_token_1_amount = 350000000
spread                 = "0.05"     # 5%
